apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  configuration: |
    provider "lxd" {
      generate_client_certificates = true
      accept_remote_certificate    = true

      remote {
        name    = "tflab2"
        address = "https://10.1.123.197:8443"
        token   = "eyJjbGllbnRfbmFtZSI6InRmbGFiIiwiZmluZ2VycHJpbnQiOiI3MWRkNGEwMDZmYmMzZmE1YWE4OGE5YjVmOTVmNTFlYWQyYThlNDY0MjIxZGY2ZjQ2ZDkwNDZlZjBmNmE0NDI0IiwiYWRkcmVzc2VzIjpbIjEwLjEuMTIzLjE5Nzo4NDQzIiwiW2ZkNDI6MToxMjM0OjEyMzQ6MjE2OjNlZmY6ZmU3MTpkY2U0XTo4NDQzIiwiMTAuMTI4LjE0LjE6ODQ0MyIsIltmZDQyOjllZDA6Y2FhYjo1ZjFiOjoxXTo4NDQzIl0sInNlY3JldCI6ImE4YWJhMjk3NzdkNzI3ZGUwYWFjY2ZjYjAyMDc4ODNjNzE5NDMyYmJhMzczODY1ZTUyZGRiZjQ4NGZkNDYwNWUiLCJleHBpcmVzX2F0IjoiMDAwMS0wMS0wMVQwMDowMDowMFoifQ=="
      }
    }

    // Modules _must_ use remote state. The provider does not persist state.
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-default"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }
      required_providers {
        lxd = {
          source = "terraform-lxd/lxd"
        }
      } 
    }
