apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: example-inline
  annotations:
    # The terraform workspace will be named 'coolbucket'. If you omit this
    # annotation it would be derived from metadata.name - e.g. 'example-inline'.
    crossplane.io/external-name: tflablxd
spec:
  forProvider:
    # Workspaces default to using a remote source - like workspace-remote.yaml.
    # For simple cases you can use an inline source to specify the content of
    # main.tf as opaque, inline HCL.
    source: Inline
    module: |
      resource "lxd_instance" "myvm1" {
        name  = "myvm"
        image = "ubuntu:22.04"
        type = "virtual-machine"
        remote = "tflab2"
        running = true

        limits = {
          cpu = 2,
          memory = "4GiB"
        }
      }
